## 3.1 넘파이 배열
### 1차원 배열 만들기

In [4]:
import numpy as np

In [5]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

type(ar)

numpy.ndarray

## 벡터화 연산

### 사칙연산

In [7]:
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

data = 2 * data
print(data)

[ 0  2  4  6  8 10 12 14 16 18]


In [10]:
a = np.array([0, 1, 2])

print(a == 2)
print(a >= 1)

[False False  True]
[False  True  True]


## 배열의 차원과 크기
배열의 차원: ndim = len(shape)

배열의 크기: shape

In [14]:
a = np.array([[0, 1, 2], [3, 4, 5], [0, 1, 2]])
print(a.ndim)
print(len(a.shape))
print(a.shape)

2
2
(3, 3)


### 배열 인덱싱
넘파이 배열의 강력한 기능은 팬시 인덱싱이라고 부르는 방법이다

In [19]:
a = np.array(range(9))
idx = np.array([True if i % 2 == 0 else False for i in range(9)])

print(a)
print(idx)

print(a[idx])

[0 1 2 3 4 5 6 7 8]
[ True False  True False  True False  True False  True]
[0 2 4 6 8]


In [20]:
print(a[a % 2 == 0])

[0 2 4 6 8]


## 연습문제

다음과 같은 행렬이 있다.

```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```

1. 이 배열에서 3의 배수를 찾아라
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라


In [24]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

idx_1 = np.array(x%3 == 0)
idx_2 = np.array(x%4 == 1)
idx_3 = idx_1 & idx_2
print(idx_1)
print(idx_2)
print(idx_3)

print(x[idx_1])
print(x[idx_2])
print(x[idx_3])

[False False  True False False  True False False  True False False  True
 False False  True False False  True False False]
[ True False False False  True False False False  True False False False
  True False False False  True False False False]
[False False False False False False False False  True False False False
 False False False False False False False False]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


## 3.2 배열의 생성과 변형
### 넘파이의 자료형

In [25]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [26]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

### 배열 생성
* zeros, ones
* zeros_like, ones_like
* empty
* arrange
* linspace, logspace

In [29]:
a = np.zeros(5)
print(a)

b = np.zeros((2, 3))
print(b)

c = np.zeros((5, 2), dtype=float)
print(c)

d = np.ones(c.shape)
print(d)

e = np.ones_like(c)
print(e)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


### 전치연산 (Transpose)
행과 열을 바꾸는 작업

In [33]:
A = np.array([[1,2,3], [4,5,6]])
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### 배열 연결 (Concatenate)
* hstack, vstack, dstack
* stack
* r...
* c...
* tile


In [36]:
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))

print(a1)
print(a2)

print(np.hstack([a1, a2])) # horizon stack

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


In [39]:
c1 = np.ones((3, 4))
c2 = np.zeros((3, 4))
c3 = np.dstack([c1, c2])

print(c1.shape)
print(c2.shape)
print(c3.shape)

print(c3) # depth stack

(3, 4)
(3, 4)
(3, 4, 2)
[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


### 연습문제 3.2.1

In [49]:
x = np.array([0 if i < 3 else 1 for i in range(5)], dtype=float)
x = np.vstack([x, x])
x = np.vstack([x, x[-1, :]])
x = np.vstack([x, np.array([i*10 for i in range(1, 6)])])
x = np.vstack([x, x[-1, :]+50])
x = np.vstack([x, x[-1, :]+50])
x = np.vstack([x, x])

print(x)


[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


## 3.3 배열의 연산
### 벡터화 연산
넘파이는 벡터화 연산 (vectorized operation)을 지원한다

벡터화 연산을 쓰면 반복문 없이 배열의 모든 원소에 대해 반복연산을 할 수 있다

벡터화 연산의 또 다른 장점은 선형 대수 공식과 동일한 아주 간단한 파이썬 코드를 작성할 수 있다는 점이다

In [51]:
%%time

x = np.arange(1, 10001)
y = np.arange(10001, 20001)

z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y [i]


CPU times: user 2.02 ms, sys: 0 ns, total: 2.02 ms
Wall time: 2.05 ms


In [52]:
%%time

z = x + y

CPU times: user 19 µs, sys: 13 µs, total: 32 µs
Wall time: 34.6 µs


### 브로드캐스팅
넘파이에서는 서로 다른 크기를 가진 두 배열의 사칙 연산도 지원한다 = 브로드캐스팅

벡터와 스칼라를 더하는 경우도 브로드캐스팅에 해당한다

In [53]:
x = np.arange(5)
y = np.ones_like(x)

print(x + y)
print(x + 1)

[1 2 3 4 5]
[1 2 3 4 5]


In [54]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
print(x)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [56]:
y = np.arange(5)[:, np.newaxis]
print(y)

print(x + y)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


### 차원 축소 연산 (dimension reduction)
* min, max, argmin, argmax
* sum, mean, median, std, var
* all, any

In [58]:
x = np.array([1, 2, 3, 4])
print("sum: ", np.sum(x))
print("min: ", x.min())
print("max: ", x.max())
print("argmin: ", x.argmin()) # 최솟값의 위치
print("argmax: ", x.argmax()) # 최댓값의 위치
print("mean: ", x.mean())
print("median: ", np.median(x))
print("all: ", np.all([True, True, False]))
print("any: ", np.any([True, True, False]))

sum:  10
min:  1
max:  4
argmin:  0
argmax:  3
mean:  2.5
median:  2.5
all:  False
any:  True


연산의 대상이 2차원 이상인 경우에는 어느 차원으로 계산할지를 axis 인수를 사용하여 지시한다

In [70]:
x = np.array([[1, 1, 1], [2, 2, 2]])
x.sum()
x.sum(axis=0)
x.sum(axis=1)

print("{} => {}".format(x.shape, x))
print("{} => {}".format(x.sum(axis=0).shape, x.sum(axis=0)))
print("{} => {}".format(x.sum(axis=1).shape, x.sum(axis=1)))

(2, 3) => [[1 1 1]
 [2 2 2]]
(3,) => [3 3 3]
(2,) => [3 6]


### 정렬 (Sort)
sort 메서드는 in-place 메서드이므로 주의를 기울어야 한다

In [76]:
a = np.array([[4, 3, 5 ,7], [1, 12, 11, 9], [2, 15, 1, 14]])

print(np.sort(a.copy())) # axis=1과 동일
print(np.sort(a.copy(), axis=0))
print(np.sort(a.copy(), axis=1))
print(a)

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
[[ 1  3  1  7]
 [ 2 12  5  9]
 [ 4 15 11 14]]
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
[[ 4  3  5  7]
 [ 1 12 11  9]
 [ 2 15  1 14]]


In [82]:
idx = np.argsort(a)
print(idx)

[[1 0 2 3]
 [0 3 2 1]
 [2 0 3 1]]


### 연습문제 3.3.2

In [95]:
score = np.array([[  1,    2,    3,    4],
                [ 46,   99,  100,   71],
                [ 81,   59,   90,  100]])

print(score[:, np.argsort(score[1, :])])


[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


## 3.4 기술 통계 (descriptive statistics)
* count
* mean, average
* variance
* standard deviation
* maximum
* minimum
* median
* quartile

In [97]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [99]:
print("length: ", len(x))
print("mean: ", np.mean(x))
print("var : ", np.var(x))
print("std : ", np.std(x))
print("median: ", np.median(x))
print("0/4 quarter: ", np.percentile(x, 0))
print("1/4 quarter: ", np.percentile(x, 25))
print("2/4 quarter: ", np.percentile(x, 50))
print("3/4 quarter: ", np.percentile(x, 100))

length:  26
mean:  4.8076923076923075
var :  115.23224852071006
std :  10.734628476137871
median:  5.0
0/4 quarter:  -24.0
1/4 quarter:  0.0
2/4 quarter:  5.0
3/4 quarter:  23.0


### 정수 데이터 카운팅
히스토그램을 그리고 싶으면 배열의 데이터를 계수할 수 있어야 한다

In [101]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

print(index)
print(count)

['a' 'b' 'c']
[2 2 1]


In [103]:
np.bincount([1, 1, 2, 2, 3], minlength=6)

array([0, 2, 2, 1, 0, 0])